version: "2"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./data/:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./data/:/usr/share/nginx/html
      - ./logs/php.log:/var/log/fpm-php.www.log
  tor:
    image: goldy/tor-hidden-service:latest
    links:
      - nginx
      - php
    depends_on:
      - nginx
      - php
    environment:
      secret_hidden_service_hosts: 80:nginx:80
      secret_hidden_service_key: "put here the private key in base64 hash string format(no '')"
      secret_hidden_service_version: "3" # you need to enter the container(or look at the logs maybe) to view the hostname(the hidden service url) or just remember the hostname that you have its private key if you decide to import it
networks:
  internal:
    driver: bridge
